### ISSUE TITLE
DayView 时间戳高度位置偏移。

### ISSUE THREAD

**Issue by Xe0n0** [pkuapp/pkuapp_iOS#19]
如果没感觉错的话似乎 DateBar 上的文本位置也有点偏移。

**Comment by lianghai** [comment]
网页和 Core Text 的文本渲染方式不同，纵向高度不一，所以原型也不便参考。先不必管它，axis 的时间戳以及 DateBar 的文本这种纯样式的小 bug 等春节后当面解决就好。
