### ISSUE TITLE
个人成绩页面

### ISSUE THREAD

**Issue by lianghai** [pkuapp/pkuapp_iOS#22]
- 课程
  - 个人成绩

整理显示来自 dean 或 portal 的个人成绩信息。将成绩信息以清晰明了的方式展示。
可按学期、课程类别……等参数排序。以学期等参数分组（类似 iOS 通讯录.app 按姓名首字母分组）。
不同级别的成绩可使用不同颜色标注。

未来可考虑通过服务器输出各种类型的成绩统计图表，并分享。

原型设计已完成：
原型设计中前两行和后两行是显示成绩的两种模式，点击成绩数字来切换，类似 iOS 的 股市.app
https://github.com/pkuapp/pkuapp_iOS_UI/blob/master/espresso/courses/grades.html
https://github.com/pkuapp/pkuapp_iOS_UI/blob/master/output/grades.png

**Comment by coolgene** [comment]
:(
