### ISSUE TITLE
更换字体为 Hiragino Sans GB 后用户协议显示不正常

### ISSUE THREAD

**Issue by xhacker** [pkuapp/pkuapp_iOS#25]
截图在此：http://cl.ly/2r1433031n0R1P3X0f2B
当然这应该不算一个 bug。

**Comment by Xe0n0** [comment]
好吧！

**Comment by lianghai** [comment]
嗯，Hiragino Sans GB 的 leading 数据比较诡异，会影响行高。
而这个出问题的 cell 又没有依据 CoreText 提供的行高来计算自己的高度，所以出问题。
应该改成动态计算的。
