### ISSUE TITLE
中小问题批量修正

### ISSUE THREAD

**Issue by lianghai** [pkuapp/pkuapp_iOS#27]
1. 通知区域 cell 排版调整（增大事件标题字号），普通 cell 也加上背景图 **DONE**
2. 首屏导航栏标题换成图 **DONE**
3. 网关问题见 #24 和 #26
4. DayView 精确定位问题，见 #18 和 #19
5. 空闲教室的 launcher 命名、导航栏命名不统一 (**DONE**)，更新无状态指示，教学楼未分类（公用、院系），点击教学楼后应先转换页面再载入信息
6. 日程介面工具栏整理，本周和今天按钮
7. 添加作业、登录介面都使用全局背景色和导航栏样式 **DONE**
8. 日程的单日介面切换时的横向滚动效果
9. 日程默认跳转到今天和当前时间
10. 回到主屏时刷新通知区域
11. 登录时第一次失败则永久失败
12. 升级用户协议页面。展现 app 权限。
13. 调整首屏图标排序
14. 关闭日程周视图
15. 编辑作业（删除、完成） **DONE**
16. 优化添加作业介面 **DONE**
17. 课程信息页面上课地点 cell 高度有误
18. 在通知区域增加「无作业」占位符，使用户便于添加作业
19. 通知区域无法显示每周多次进行的课程的「下一节课」时间。

**Comment by coolgene** [comment]
1. 登陆时验证码读取出错之后的处理逻辑。
2. 从 elective 上读取的课程没有上课地点（更新：是不是只有专业课没有地点？）
3. 首屏出现一个 Label，正常情况？ 图片：http://d.pr/4ars
4. 教室查询介面教室编号重复（更新：刚才测试，Android 上面也是这样），图片：http://d.pr/XU0E

以上是在 iPhone 3G 上出现的。另外：
1. 日程介面中的日介面是否能够自动转到当前时间，而不是转到0点。

**Comment by lianghai** [comment]
以后不要再用 CloudApp 了，它被墙了，访问起来很麻烦。用 Droplr 吧。

**Comment by coolgene** [comment]
okay.

## 

ZHANG Ta
颐和园路5号

在 2012年2月13日星期一，下午2:28，梁海 写道：
