### ISSUE TITLE
部署 Google Analytics

### ISSUE THREAD

**Issue by coolgene** [pkuapp/pkuapp_iOS#28]
我们可以用 Google Analytics 来收集匿名数据。

相关资料：
- http://code.google.com/intl/zh-CN/apis/analytics/docs/mobile/ios.html
- https://www.google.com/analytics/web/?pli=1#management/Property/a28278859w55652804p56676739/%3FpropertyComposite.tabId%3DtrackingCodeTab/

另外，我们的跟踪 ID 是 UA-28278859-3

**Comment by coolgene** [comment]
昊天看这个是不是可以加上了？

**Comment by Xe0n0** [comment]
我尽快。现在收不到邮件通知不知道为什么。

**Comment by jiayexie** [comment]
我前一段时间也是收不到邮件通知，后来更新了邮箱的ssh key就好了。不知道你是不是这个原因。
