### ISSUE TITLE
登陆时错误提示－系列

### ISSUE THREAD

**Issue by coolgene** [pkuapp/pkuapp_iOS#31]
1. 登陆综合信息服务账号那一步总是显示：-[_NSCFSet setDeanid:]: unr...
2. 另一种提示，如图：http://d.pr/AArF

来自用户反馈

**Comment by Xe0n0** [comment]
这两个人的联系方式是？我亲自联系一下。

**Comment by coolgene** [comment]
one of them: thyz191fy@pku.edu.cn

2012/3/20 ZeR0-Wu <
reply@reply.github.com

**Comment by coolgene** [comment]
another: mobile 15210599379

2012/3/21 ZHANG Ta coolgene@gmail.com
